### ISSUE TITLE
`npm start` error

### ISSUE THREAD

**Issue by alicelyy** [codebase-berkeley/ethical-internal-website#74]
I'm getting the following error running `npm start`:
```
> ethical-internal-website@0.1.0 start /home/alclol/Documents/ethical-internal-website
> react-scripts start

Attempting to bind to HOST environment variable: linux-zoyn
If this was unintentional, check that you haven't mistakenly set it in your shell.
Learn more here: https://bit.ly/CRA-advanced-config

events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND linux-zoyn
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
Emitted 'error' event on Server instance at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1485:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:17) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'linux-zoyn'
}
```
Tried `npm cache clean --force` as recommended on stackoverflow but this problem persists.

**Comment by alicelyy** [comment]
Sorry that was kinda dumb.
`export HOST=localhost` solved the problem.
